version: "3.9"
services:
  app:
    image: alieb01/finalprojecttrends
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_USER: prostgres
      POSTGRES_PASSWORD: alawi123
      POSTGRES_DB: postgres
    ports:
      - "5434:5433"
